# This file contains the languages supported by Steam, as documented at:
# https://partner.steamgames.com/doc/store/localization/languages

SUPPORTED_LANGUAGES = {
    "arabic": "arabic",
    "bulgarian": "bulgarian",
    "schinese": "schinese",
    "tchinese": "tchinese",
    "czech": "czech",
    "danish": "danish",
    "dutch": "dutch",
    "english": "english",
    "finnish": "finnish",
    "french": "french",
    "german": "german",
    "greek": "greek",
    "hungarian": "hungarian",
    "indonesian": "indonesian",
    "italian": "italian",
    "japanese": "japanese",
    "koreana": "koreana",
    "norwegian": "norwegian",
    "polish": "polish",
    "portuguese": "portuguese",
    "brazilian": "brazilian",
    "romanian": "romanian",
    "russian": "russian",
    "spanish": "spanish",
    "latam": "latam",
    "swedish": "swedish",
    "thai": "thai",
    "turkish": "turkish",
    "ukrainian": "ukrainian",
    "vietnamese": "vietnamese",
}
